version: 0.0
os: linux

files:
  - source: CloudNativeWebApp/target/CloudNativeWebApp-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu

hooks:
  ApplicationStop:
   - location: ./codedeploy/StopApplication.sh
     timeout: 180
     runas: ubuntu
  ApplicationStart:
   - location: ./codedeploy/StartApplication.sh
     timeout: 180
     runas: ubuntu