version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu

hooks:
  ApplicationStop:
   - location: scripts/StopApplication.sh
     timeout: 180
     runas: ubuntu
  ApplicationStart:
   - location: scripts/StartApplication.sh
     timeout: 180
     runas: ubuntu