version: 0.0
os: linux

files:
  - source: CloudNativeWebApp/target/CloudNativeWebApp-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu
  - source: cloudwatch-config.json
    destination: /home/ubuntu
hooks:
  ApplicationStop:
   - location: ./scripts/StopApplication.sh
     timeout: 180
     runas: ubuntu
  ApplicationStart:
   - location: ./scripts/StartApplication.sh
     timeout: 180
     runas: ubuntu